name: Continuous Integration

on:
  push:
    branches: [ "master", "Version2" ]
  pull_request:
    branches: [ "master", "Version2" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
     
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore Endangered_animals.sln

      - name: Build solution
        run: msbuild Endangered_animals.sln /p:Configuration=Release
      
      
      - name: Install VSTest platform
        uses: darenm/Setup-VSTest@v1

      - name: Run unit tests
        run: |
          vstest.console "C:\Users\corna\source\repos\Endangered_animals\Endangered_animalsTests\bin\Debug\Endangered_animalsTests.dll"
      - name: Deploy - zip build output
        run: |
          mkdir deploy
          xcopy /s /y Endangered_animals\bin\Release deploy\
          powershell Compress-Archive -Path deploy\* -DestinationPath deployed_build.zip